services:
  db:
    hostname: db
    image: postgres:17.4-bookworm
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/volumes/db:/var/lib/postgresql/data